apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2                      # Número de copias (pods)
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx                # Tiene que coincidir con el selector
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80